version = 3.11.5

align {
  preset = none
  stripMargin = true
}

assumeStandardLibraryStripMargin = true

binPack {
  importSelectors = fold
}

danglingParentheses {
  preset = true
}

docstrings {
  style = Asterisk
  wrap = fold
}

maxColumn = 100

newlines {
  avoidForSimpleOverflow = all
  ignoreInSyntax = false
  source = fold
}

project {
  excludeFilters = [ "\\Wsbt-test\\W" ]
  git = true
  layout = StandardConvention
}

runner {
  dialect = scala3
}

rewrite {
  imports {
    selectors = fold
    removeRedundantSelectors = true
    sort = ascii
    groups = [
      ["sbt\\..*"],
      ["java.?\\..*"],
      ["scala\\..*"],
      ["org\\..*"],
      ["com\\..*"],
    ]
  }
  redundantBraces {
    preset = all
    oneStatApply {
      parensMaxSpan = 300
      bracesMinSpan = 300
    }
  }
  redundantParens {
    preset = all
  }
  rules = [
    AvoidInfix,
    Imports,
    RedundantBraces,
    RedundantParens,
    SortModifiers,
  ]
  scala3 {
    convertToNewSyntax = true
    newSyntax.control = false
  }
  sortModifiers.preset = styleGuide
  trailingCommas.style = always
}
